// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feupxyvghnlvukiogxxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZldXB4eXZnaG5sdnVraW9neHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1MzQxNTUsImV4cCI6MjA5MjExMDE1NX0.1zKEV_KDJOVoht0UBkMVkP0cZcsY7F__RKqVIV_a1Eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});

